# Site settings
title: Marin Bukov, PhD
email: mgbukov(at)phys.uni-sofia.bg
address: Faculty of Physics <br> Sofia University <br> office B42 <br> 5 James Bourchier blvd. <br> Sofia 1164, Bulgaria
gmaps_coords: 42.673533, 23.329888,17z

description: > # this means to ignore newlines until "baseurl:"
  I study the dynamics of out-of-equilibrium many-body quantum and classical systems. My research focusses on 
  Condensed Matter Physics, Ultracold Atoms, and Statistical Mechanics, and the interplay between Machine
  Learning and Physics. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://mgbukov.github.io/" # the base hostname & protocol for your site

#twitter_username: jekyllrb
github_username:  mgbukov
#google_play: 'GDGX'
#google_plus_com: '109485346959707049693'  # Community link
#google_plus_per: '+GDGManagua'  #Personal link
#facebook_app_id: 12345
linkedin_id: marin-bukov-80b69312a

# Layout settings
header_type: default  # values [ drawer, default ]
post_type: highlight    # values [ highlight, default ]
pagination_type: default  # values [ ops, default ]

more_vert:
  option3:
    name: scientific papers
    link: https://arxiv.org/search/?query=%22Bukov%22&searchtype=author&order=-announced_date_first&size=50 
disqus: false
#disqus_shortname: 'gdgmanagua'

# Build settings
markdown: kramdown # kramdown, redcarpet

# Google Analytics
google_analytics: UA-106553509-1
